name: Colin Dash - Godot 4.3 Build

on:
  push:
    branches:
      - main  # Запуск при пуше в main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать вручную через GitHub Actions UI

jobs:
  export_game:
    runs-on: ubuntu-latest  # Используем Ubuntu

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4  # Обновляем версию checkout

      - name: Установить Godot 4.3
        uses: tzachshabtay/godot-ci@v1
        with:
          version: "4.3"  # Указываем версию Godot 4.3
          export_presets: "export_presets.cfg"  # Файл настроек экспорта

      - name: Собрать игру "Colin Dash" для Windows
        run: |
          mkdir -p build/windows
          godot --headless --export-release "Windows Desktop" build/windows/colin-dash.exe

      - name: Собрать игру "Colin Dash" для Linux
        run: |
          mkdir -p build/linux
          godot --headless --export-release "Linux/X11" build/linux/colin-dash.x86_64

      - name: Загружать артефакты сборки
        uses: actions/upload-artifact@v4  # Обновляем версию
        with:
          name: colin-dash-build
          path: build/

