name: Colin Dash - Godot 4.3 Build (Linux only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установить Godot 4.3
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip
          chmod +x Godot_v4.3-stable_linux.x86_64
          sudo mv Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot

      - name: Установить экспортные шаблоны
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.3.stable/
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          unzip Godot_v4.3-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/
          mv ~/.local/share/godot/export_templates/templates/* ~/.local/share/godot/export_templates/4.3.stable/
          ls -lah ~/.local/share/godot/export_templates/4.3.stable/

      - name: Собрать игру "Colin Dash" для Linux
        run: |
          mkdir -p build/linux
          godot --headless --export-release "Linux" build/linux/colin-dash.x86_64

      - name: Загружать артефакты сборки
        uses: actions/upload-artifact@v4
        with:
          name: colin-dash-linux
          path: build/

      - name: Опубликовать в GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/linux/colin-dash.x86_64
          tag_name: latest
          release_name: "Latest Linux Build"
          body: "Автоматическая сборка игры Colin Dash для Linux"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Опубликовать в GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: "Latest Linux Build"
          tag_name: latest
          body: "Автоматическая сборка игры Colin Dash для Linux"
          files: build/linux/colin-dash.x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ZOTOV }}

